### ISSUE TITLE
Showcasing/streaming your mod

### ISSUE THREAD

**Issue by Lactic68** [RivalAUT/FS22_VineHarvestHandTool#2]
Hi @RivalAUT,

I'm Vincent from the french [Univers Simu](https://www.univers-simu.com/) team. Congratulations for your mod ! This is a great idea !

Can we have your agreement to showcase/stream your mod ? We will link to this github unless you would like something else of course.

Best regards,

Vincent

**Comment by RivalAUT** [comment]
Hi!

Of course you can show this mod.

Best regards

**Comment by Lactic68** [comment]
Great, thank you :)
