### ISSUE TITLE
Error: failed to create placed resource (BufferPool)

### ISSUE THREAD

**Issue by Lactic68** [RivalAUT/FS22_VineHarvestHandTool#3]
Hi,
My game sometimes crashes when I buy the grappe pallet

Map : Haut-Beyleron

Log here : [https://pastebin.com/fuAuhx48](https://pastebin.com/fuAuhx48)

**Comment by RivalAUT** [comment]
Hi,
thats interesting... The grape pallet is from the base game.
After some searching it seems to be a - kind of - random error, maybe triggered by textures. As these are from the base game, I can't do anything there.
https://gdn.giants-software.com/thread.php?categoryId=4&threadId=9602

**Comment by Lactic68** [comment]
Well, thank you for your research. I close this issue than.
